accountIdentifier: AccountIdentifier
apiKey: pat.xxx.yyy.zzz
targetProjects:
  - "target_project1"
  - "target_project2"
excludeProjects:
  - "exclude_project1"
  - "exclude_project2"
targetServices:
  - "service1": "project1"
  - "service2": "project2"
excludeServices:
  - "exclude_service1": "project1"
  - "exclude_service2": "project2"
gitDetails:
  branch_name: "migration"
  commit_message: "Migrating piplines from inline to remote"
  connector_ref: "account.HarnessRemoteTest"
  repo_name: "HarnessRemoteTest"
fileStoreConfig:
  branch: "migration"
  url: "https://github.com/aleksa11010/HarnessRemoteMigrator.git"
