package harness

// Generated by https://quicktype.io

type Projects struct {
	Status        string       `json:"status"`
	Data          ProjectsData `json:"data"`
	MetaData      interface{}  `json:"metaData"`
	CorrelationID string       `json:"correlationId"`
}

type ProjectsData struct {
	TotalPages    int64             `json:"totalPages"`
	TotalItems    int64             `json:"totalItems"`
	PageItemCount int64             `json:"pageItemCount"`
	PageSize      int64             `json:"pageSize"`
	Content       []ProjectsContent `json:"content"`
	PageIndex     int64             `json:"pageIndex"`
	Empty         bool              `json:"empty"`
	PageToken     interface{}       `json:"pageToken"`
}

type ProjectsContent struct {
	Project        Project `json:"project"`
	CreatedAt      *int64  `json:"createdAt"`
	LastModifiedAt int64   `json:"lastModifiedAt"`
}

type Project struct {
	OrgIdentifier OrgIdentifier    `json:"orgIdentifier"`
	Identifier    string           `json:"identifier"`
	Name          string           `json:"name"`
	Color         string           `json:"color"`
	Modules       []ProjectsModule `json:"modules"`
	Description   string           `json:"description"`
	Tags          ProjectsTags     `json:"tags"`
}

type ProjectsTags struct {
	Owner                  *string `json:"owner,omitempty"`
	FinOps                 *string `json:"FinOps,omitempty"`
	SRMStandalone          *string `json:"SRM Standalone,omitempty"`
	SloSLI                 *string `json:"SLO/SLI,omitempty"`
	ErrorTracking          *string `json:"Error Tracking,omitempty"`
	DeploymentVerification *string `json:"Deployment Verification,omitempty"`
	ServiceHealth          *string `json:"Service Health,omitempty"`
}

type ProjectsModule string

type OrgIdentifier string
