package harness

// Generated by https://quicktype.io

type Service struct {
	Service ServiceClass `json:"service"`
	Created int64        `json:"created"`
	Updated int64        `json:"updated"`
}

type ServiceClass struct {
	Account     string      `json:"account"`
	Identifier  string      `json:"identifier"`
	Org         string      `json:"org"`
	Project     string      `json:"project"`
	Name        string      `json:"name"`
	Description interface{} `json:"description"`
	Tags        ServiceTags `json:"tags"`
	YAML        string      `json:"yaml"`
}

type ServiceTags struct {
	Tags []string
}

// ServiceYaml
type ServiceEntity struct {
	Service ServiceYaml `yaml:"service"`
}
type StoreSpec struct {
	ConnectorRef string   `yaml:"connectorRef"`
	GitFetchType string   `yaml:"gitFetchType"`
	Paths        []string `yaml:"paths"`
	Branch       string   `yaml:"branch"`
}
type Store struct {
	Type string    `yaml:"type"`
	Spec StoreSpec `yaml:"spec"`
}
type ManifestSpec struct {
	Store                     Store `yaml:"store"`
	SkipResourceVersioning    bool  `yaml:"skipResourceVersioning"`
	EnableDeclarativeRollback bool  `yaml:"enableDeclarativeRollback"`
}
type Manifest struct {
	Identifier string    `yaml:"identifier"`
	Type       string    `yaml:"type"`
	Spec       StoreSpec `yaml:"spec"`
}
type Manifests struct {
	Manifest Manifest `yaml:"manifest"`
}
type ServiceDefinitionSpec struct {
	Manifests []Manifests `yaml:"manifests"`
}
type ServiceDefinition struct {
	ServiceDefinitionSpec ServiceDefinitionSpec `yaml:"spec"`
	Type                  string                `yaml:"type"`
}
type ServiceYaml struct {
	Name              string            `yaml:"name"`
	Identifier        string            `yaml:"identifier"`
	OrgIdentifier     string            `yaml:"orgIdentifier"`
	ProjectIdentifier string            `yaml:"projectIdentifier"`
	ServiceDefinition ServiceDefinition `yaml:"serviceDefinition"`
}
