package harness

import (
	"log"

	"gopkg.in/yaml.v2"
)

// Generated by https://quicktype.io

type Service struct {
	Service ServiceClass `json:"service"`
	Created int64        `json:"created"`
	Updated int64        `json:"updated"`
}

type ServiceClass struct {
	Account     string      `json:"account"`
	Identifier  string      `json:"identifier"`
	Org         string      `json:"org"`
	Project     string      `json:"project"`
	Name        string      `json:"name"`
	Description interface{} `json:"description"`
	Tags        ServiceTags `json:"tags"`
	YAML        string      `json:"yaml"`
	StoreType   string      `json:"storeType"`
}

type ServiceTags struct {
	Tags []string
}
type ServiceYaml struct {
	Service struct {
		Name              string            `yaml:"name"`
		Identifier        string            `yaml:"identifier"`
		Description       string            `yaml:"description"`
		Tags              map[string]string `yaml:"tags"`
		GitOpsEnabled     bool              `yaml:"gitOpsEnabled"`
		ServiceDefinition struct {
			Type string `yaml:"type"`
			Spec struct {
				Variables []struct {
					Name     string `yaml:"name"`
					Type     string `yaml:"type"`
					Value    string `yaml:"value"`
					Required bool   `yaml:"required"`
				} `yaml:"variables"`
				Artifacts struct {
					Primary struct {
						PrimaryArtifactRef string `yaml:"primaryArtifactRef"`
						Sources            []struct {
							Spec struct {
								ConnectorRef string `yaml:"connectorRef"`
								ImagePath    string `yaml:"imagePath"`
								Tag          string `yaml:"tag"`
								Region       string `yaml:"region"`
							} `yaml:"spec"`
							Identifier string `yaml:"identifier"`
							Type       string `yaml:"type"`
						} `yaml:"sources"`
					} `yaml:"primary"`
				} `yaml:"artifacts"`
				Manifests []struct {
					Manifest struct {
						Identifier string `yaml:"identifier"`
						Type       string `yaml:"type"`
						Spec       struct {
							Store struct {
								Type string `yaml:"type"`
								Spec struct {
									ConnectorRef              string   `yaml:"connectorRef"`
									GitFetchType              string   `yaml:"gitFetchType"`
									Paths                     []string `yaml:"paths"`
									Branch                    string   `yaml:"branch"`
									Files                     []string `yaml:"files"`
									SkipResourceVersioning    bool     `yaml:"skipResourceVersioning"`
									EnableDeclarativeRollback bool     `yaml:"enableDeclarativeRollback"`
								} `yaml:"spec"`
								ValuesPaths []string `yaml:"valuesPaths"`
							} `yaml:"store"`
							ChartName              string `yaml:"chartName"`
							ChartVersion           string `yaml:"chartVersion"`
							HelmVersion            string `yaml:"helmVersion"`
							SkipResourceVersioning bool   `yaml:"skipResourceVersioning"`
						} `yaml:"spec"`
					} `yaml:"manifest"`
				} `yaml:"manifests"`
				ConfigFiles []struct {
					ConfigFile struct {
						Identifier string `yaml:"identifier"`
						Spec       struct {
							Store struct {
								Spec struct {
									SecretFiles []string `yaml:"secretFiles"`
								} `yaml:"spec"`
								Type string `yaml:"type"`
							} `yaml:"store"`
							ConfigFileAttributeStepParameters struct {
								Store struct {
									Type string `yaml:"type"`
									Spec struct {
										Type        string   `yaml:"type"`
										SecretFiles []string `yaml:"secretFiles"`
									} `yaml:"spec"`
								} `yaml:"store"`
							} `yaml:"configFileAttributeStepParameters"`
						} `yaml:"spec"`
					} `yaml:"configFile"`
				} `yaml:"configFiles"`
			} `yaml:"spec"`
		} `yaml:"serviceDefinition"`
	} `yaml:"service"`
}

type ServiceRequest struct {
	Name              string      `json:"name"`
	Identifier        string      `json:"identifier"`
	Tags              ServiceTags `json:"tags"`
	ProjectIdentifier string      `json:"projectIdentifier"`
	OrgIdentifier     string      `json:"orgIdentifier"`
	YAML              string      `json:"yaml"`
}

func (s *ServiceClass) ParseYAML() (*ServiceYaml, error) {
	serviceYaml := &ServiceYaml{}
	err := yaml.Unmarshal([]byte(s.YAML), &serviceYaml)
	if err != nil {
		log.Fatalf("Unmarshal: %v", err)
	}

	return serviceYaml, nil
}

func (s *ServiceClass) UpdateService(api *APIRequest) error {
	service := &ServiceRequest{
		Name:              s.Name,
		Identifier:        s.Identifier,
		ProjectIdentifier: s.Project,
		OrgIdentifier:     s.Org,
		YAML:              s.YAML,
	}
	err := api.UpdateService(*service, s.Account)
	if err != nil {
		return err
	}
	return nil
}
