package harness

// Generated by https://quicktype.io

type Templates []Template

type Template struct {
	Account        string     `json:"account"`
	Org            string     `json:"org"`
	Project        string     `json:"project"`
	Identifier     string     `json:"identifier"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	Tags           Tags       `json:"tags"`
	VersionLabel   string     `json:"version_label"`
	EntityType     string     `json:"entity_type"`
	ChildType      string     `json:"child_type"`
	Scope          string     `json:"scope"`
	Version        int64      `json:"version"`
	GitDetails     GitDetails `json:"git_details"`
	Updated        int64      `json:"updated"`
	StoreType      string     `json:"store_type"`
	ConnectorRef   string     `json:"connector_ref"`
	YAMLVersion    string     `json:"yaml_version"`
	StableTemplate bool       `json:"stable_template"`
}
